'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CarFront, Check, CreditCard, LoaderCircle, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { CHECKOUT_KEY, ORDERS_KEY, readDemoUser, type DemoUser } from '@/lib/demo-auth';

type Draft = { vehicle: { id:number; brand:string; model:string; image:string; dailyRate:number }; startDate:string; endDate:string; pickupCity:string; returnCity:string; customer:string; email:string; days:number; totalCost:number };
const money = (value:number) => `R${value.toLocaleString('en-ZA')}`;

export function CheckoutPage() {
  const [draft,setDraft] = useState<Draft|null>(null); const [user,setUser] = useState<DemoUser|null>(null);
  const [stage,setStage] = useState<'ready'|'processing'|'success'>('ready'); const [reference,setReference] = useState('');
  const [method,setMethod] = useState<'card'|'apple'|'google'>('card');
  const [card,setCard] = useState({name:'Demo Customer',number:'4242 4242 4242 4242',expiry:'12/30',cvc:'123'});
  useEffect(()=>{ const current=readDemoUser(); setUser(current); setCard(x=>({...x,name:current?.name||x.name})); try{setDraft(JSON.parse(localStorage.getItem(CHECKOUT_KEY)||'null'));}catch{} },[]);
  const pay = async (event:FormEvent) => { event.preventDefault(); if(!draft||stage!=='ready')return; setStage('processing'); await new Promise(r=>setTimeout(r,1900)); const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:user?.name||draft.customer,email:user?.email||draft.email,vehicleId:draft.vehicle.id,vehicle:`${draft.vehicle.brand} ${draft.vehicle.model}`,startDate:draft.startDate,endDate:draft.endDate,pickupCity:draft.pickupCity,returnCity:draft.returnCity,totalCost:draft.totalCost})}); const booking=await response.json(); const ref=booking.id||`BK-${Date.now().toString().slice(-6)}`; setReference(ref); const orders=JSON.parse(localStorage.getItem(ORDERS_KEY)||'[]'); localStorage.setItem(ORDERS_KEY,JSON.stringify([{reference:ref,vehicle:`${draft.vehicle.brand} ${draft.vehicle.model}`,amount:draft.totalCost,date:new Date().toISOString(),method},...orders])); localStorage.removeItem(CHECKOUT_KEY); setStage('success'); };
  if(!user) return <Empty title="Sign in to continue" copy="Your selected car is waiting. Sign in with a local demo account to reach checkout." href="/login?returnTo=/checkout" action="Sign in" />;
  if(!draft) return <Empty title="Your checkout is empty" copy="Choose a vehicle and rental dates to begin a new booking." href="/#browse" action="Browse vehicles" />;
  if(stage==='success') return <main className="grid min-h-screen place-items-center bg-[#f5f5f7] p-5"><section className="page-enter w-full max-w-xl rounded-[36px] bg-white p-8 text-center shadow-[0_30px_90px_rgba(0,0,0,.1)] sm:p-14"><div className="success-pop mx-auto grid size-20 place-items-center rounded-full bg-emerald-500 text-white"><Check className="size-10" /></div><p className="mt-8 text-sm font-semibold text-emerald-600">SIMULATED PAYMENT APPROVED</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">You’re ready to drive.</h1><p className="mt-4 text-black/50">Your demo booking for the {draft.vehicle.brand} {draft.vehicle.model} is confirmed.</p><div className="mt-8 rounded-3xl bg-[#f5f5f7] p-6"><p className="text-xs text-black/40">BOOKING REFERENCE</p><p className="mt-1 text-2xl font-semibold">{reference}</p><div className="my-5 h-px bg-black/[.07]"/><div className="flex justify-between text-sm"><span className="text-black/45">Simulated total</span><strong>{money(draft.totalCost)}</strong></div></div><a href="/#browse" className="mt-8 inline-flex h-12 items-center gap-2 rounded-full bg-black px-7 text-sm font-medium text-white">Explore more cars <ArrowRight className="size-4"/></a></section></main>;
  return <main className="page-enter min-h-screen bg-[#f5f5f7] text-[#1d1d1f]"><header className="border-b border-black/5 bg-white/80 backdrop-blur-2xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><a href="/" className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-full bg-black text-white"><CarFront className="size-4"/></span>Drift</a><span className="flex items-center gap-2 text-xs text-black/45"><LockKeyhole className="size-4"/>Demo secure checkout</span></div></header><div className="mx-auto max-w-6xl px-5 py-8 sm:py-14"><a href="/" className="inline-flex items-center gap-2 text-sm text-black/45"><ArrowLeft className="size-4"/>Back to catalogue</a><div className="mt-7 grid gap-7 lg:grid-cols-[.88fr_1.12fr]">
    <section className="h-fit overflow-hidden rounded-[32px] bg-black text-white shadow-2xl"><div className="relative aspect-[16/10] overflow-hidden"><img src={draft.vehicle.image} alt={`${draft.vehicle.brand} ${draft.vehicle.model}`} className="hero-drift h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"/><div className="absolute bottom-6 left-6"><p className="text-sm text-white/55">Your drive</p><h1 className="text-3xl font-semibold tracking-tight">{draft.vehicle.brand} {draft.vehicle.model}</h1></div></div><div className="p-7"><div className="grid grid-cols-2 gap-5 text-sm"><Summary label="Pick-up" value={`${draft.startDate} · ${draft.pickupCity}`}/><Summary label="Return" value={`${draft.endDate} · ${draft.returnCity}`}/><Summary label="Rental length" value={`${draft.days} days`}/><Summary label="Daily rate" value={money(draft.vehicle.dailyRate)}/></div><div className="my-6 h-px bg-white/10"/><div className="flex items-end justify-between"><span className="text-white/55">Total</span><strong className="text-3xl">{money(draft.totalCost)}</strong></div></div></section>
    <form onSubmit={pay} className="rounded-[32px] bg-white p-6 shadow-sm sm:p-9"><p className="text-sm font-semibold text-[#0071e3]">PAYMENT</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Complete your booking.</h2><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck className="mr-2 inline size-4"/><strong>Simulation only.</strong> No card is charged. Use the demo card details shown below—never enter a real card.</div><div className="mt-6 grid grid-cols-3 gap-2">{([['card','Card'],['apple',' Pay'],['google','G Pay']] as const).map(([id,label])=><button type="button" key={id} onClick={()=>setMethod(id)} className={`h-12 rounded-2xl border text-sm font-medium transition ${method===id?'border-black bg-black text-white':'border-black/10 hover:border-black/25'}`}>{label}</button>)}</div>
      {method==='card'?<div className="mt-6 space-y-4"><label className="block text-xs font-medium text-black/55">Name on card<Input className="mt-2 h-12 rounded-2xl" value={card.name} onChange={e=>setCard({...card,name:e.target.value})}/></label><label className="block text-xs font-medium text-black/55">Demo card number<div className="relative mt-2"><CreditCard className="absolute left-4 top-3.5 size-5 text-black/30"/><Input className="h-12 rounded-2xl pl-12" inputMode="numeric" value={card.number} onChange={e=>setCard({...card,number:e.target.value})}/></div></label><div className="grid grid-cols-2 gap-4"><label className="block text-xs font-medium text-black/55">Expiry<Input className="mt-2 h-12 rounded-2xl" value={card.expiry} onChange={e=>setCard({...card,expiry:e.target.value})}/></label><label className="block text-xs font-medium text-black/55">CVC<Input className="mt-2 h-12 rounded-2xl" value={card.cvc} onChange={e=>setCard({...card,cvc:e.target.value})}/></label></div></div>:<div className="mt-6 rounded-3xl bg-[#f5f5f7] p-8 text-center"><p className="text-4xl">{method==='apple'?'':'G'}</p><p className="mt-3 font-medium">{method==='apple'?'Apple Pay':'Google Pay'} demo</p><p className="mt-1 text-xs text-black/40">No wallet will open and no money will move.</p></div>}
      <Button disabled={stage==='processing'} className="payment-shimmer mt-7 h-13 w-full rounded-full bg-[#0071e3] text-white hover:bg-[#0077ed]">{stage==='processing'?<><LoaderCircle className="animate-spin"/>Simulating payment…</>:<>Pay {money(draft.totalCost)} <LockKeyhole/></>}</Button><p className="mt-4 text-center text-[11px] leading-4 text-black/35">By continuing, you confirm this is an educational prototype transaction.</p>
    </form></div></div></main>;
}
function Summary({label,value}:{label:string;value:string}){return <div><p className="text-xs text-white/40">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Empty({title,copy,href,action}:{title:string;copy:string;href:string;action:string}){return <main className="grid min-h-screen place-items-center bg-[#f5f5f7] p-5"><section className="rounded-[32px] bg-white p-10 text-center shadow-sm"><CarFront className="mx-auto size-9 text-black/20"/><h1 className="mt-5 text-3xl font-semibold tracking-tight">{title}</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-black/45">{copy}</p><a href={href} className="mt-7 inline-flex h-11 items-center gap-2 rounded-full bg-black px-6 text-sm text-white">{action}<ArrowRight className="size-4"/></a></section></main>}
