'use client';

import { Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows, OrbitControls, RoundedBox } from '@react-three/drei';
import { Color, Group, MathUtils, Mesh, Vector3 } from 'three';
import { ArrowDown, ArrowLeft, CarFront, Check, DoorOpen, RotateCcw, Wind } from 'lucide-react';
import { Button } from '@/components/ui/button';

type SceneState = 'intro' | 'exterior' | 'doorOpening' | 'interior' | 'configuring' | 'returning';
type CameraPreset = 'front' | 'side' | 'rear' | 'interior';
type Config = { paint: string; upholstery: string; doorOpen: boolean; windowDown: boolean };

const paints = [{name:'Obsidian',value:'#111318'},{name:'Glacier',value:'#d9e3ea'},{name:'Velocity Blue',value:'#105cf6'},{name:'Ember',value:'#a81619'}];
const leathers = [{name:'Graphite',value:'#171717'},{name:'Saddle',value:'#7a3f21'},{name:'Cloud',value:'#ded8cd'}];
const cameraAnchors: Record<CameraPreset,{position:[number,number,number];target:[number,number,number]}> = {
  front:{position:[7,3.2,8],target:[0,.7,0]}, side:{position:[9,2.5,.2],target:[0,.65,0]}, rear:{position:[-7,2.8,-7],target:[0,.7,0]}, interior:{position:[1.25,1.7,1.15],target:[-.8,1.05,-.15]},
};

export default function CinematicCar() {
  const [progress,setProgress]=useState(0); const [explore,setExplore]=useState(false); const [preset,setPreset]=useState<CameraPreset>('front');
  const [config,setConfig]=useState<Config>({paint:paints[0].value,upholstery:leathers[1].value,doorOpen:false,windowDown:false});
  const [webgl,setWebgl]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const stageRef=useRef<HTMLElement>(null);
  useEffect(()=>{ try { const canvas=document.createElement('canvas'); setWebgl(Boolean(canvas.getContext('webgl2')||canvas.getContext('webgl'))); } catch { setWebgl(false); } },[]);
  useEffect(()=>{ const media=window.matchMedia('(prefers-reduced-motion: reduce)'); const update=()=>setReducedMotion(media.matches); update(); media.addEventListener('change',update); return()=>media.removeEventListener('change',update); },[]);
  useEffect(()=>{ const update=()=>{ if(explore||reducedMotion||!stageRef.current)return; const rect=stageRef.current.getBoundingClientRect(); const distance=stageRef.current.offsetHeight-window.innerHeight; setProgress(MathUtils.clamp(-rect.top/Math.max(distance,1),0,1)); }; update(); window.addEventListener('scroll',update,{passive:true}); return()=>window.removeEventListener('scroll',update); },[explore,reducedMotion]);
  const scene:SceneState=explore?'configuring':progress<.14?'intro':progress<.34?'exterior':progress<.5?'doorOpening':progress<.7?'interior':progress<.86?'configuring':'returning';
  const guidedPreset:CameraPreset=progress<.25?'front':progress<.46?'side':progress<.82?'interior':'rear';
  const choosePreset=(next:CameraPreset)=>{setExplore(true);setPreset(next)};
  const setDoor=(doorOpen:boolean)=>{setExplore(true);setPreset(doorOpen?'side':'front');setConfig(x=>({...x,doorOpen}))};
  return <main className="bg-[#050609] text-white"><header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/55 backdrop-blur-2xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><a href="/" className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-full bg-white text-black"><CarFront className="size-4"/></span>Drift</a><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-white/60">Concept experience · visual preview</span></div></header>
    <section ref={stageRef} className="relative h-[420vh]" aria-label="Scroll-driven Drift Concept presentation"><div className="sticky top-0 h-screen overflow-hidden">
      {webgl?<Suspense fallback={<Poster/>}><Canvas dpr={[1,1.7]} camera={{position:cameraAnchors.front.position,fov:36,near:.1,far:100}} gl={{antialias:true,alpha:false}} shadows onCreated={({gl})=>gl.setClearColor('#050609')}><fog attach="fog" args={['#050609',14,29]}/><ambientLight intensity={.65}/><directionalLight position={[4,9,6]} intensity={3.2} castShadow shadow-mapSize={[1024,1024]}/><pointLight position={[-5,3,-4]} intensity={45} color="#1b64ff"/><pointLight position={[5,2,5]} intensity={28} color="#fff1dd"/><CarScene config={config} progress={progress} guidedPreset={guidedPreset} preset={preset} explore={explore}/><ContactShadows position={[0,-.58,0]} opacity={.65} scale={15} blur={2.4} far={5}/><OrbitControls enabled={explore} enablePan={false} minDistance={4} maxDistance={13} minPolarAngle={.75} maxPolarAngle={1.5} target={[0,.7,0]}/></Canvas></Suspense>:<Poster/>}
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_55%,transparent_25%,rgba(0,0,0,.72)_100%)]"/>
      <div className="pointer-events-none absolute inset-x-0 top-24 z-10 mx-auto max-w-7xl px-5"><p className="text-xs font-semibold tracking-[.2em] text-[#64d2ff]">DRIFT CONCEPT 01</p><h1 className="mt-3 max-w-3xl text-5xl font-semibold leading-[.92] tracking-[-.065em] sm:text-7xl">Motion, made tangible.</h1><p className="mt-5 max-w-md text-base leading-7 text-white/55">A responsive concept model demonstrating Drift’s future vehicle exploration system.</p></div>
      {!explore&&<div className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 text-center"><p className="text-xs text-white/45">{sceneLabel(scene)}</p><ArrowDown className="mx-auto mt-3 size-5 animate-bounce text-white/55"/></div>}
      <div className="absolute bottom-5 right-5 z-20 hidden w-[320px] rounded-[28px] border border-white/10 bg-black/65 p-5 backdrop-blur-2xl lg:block"><Configurator {...{config,setConfig,explore,setExplore,preset,choosePreset,setDoor}}/></div>
    </div></section>
    <section className="relative z-20 -mt-[100vh] bg-gradient-to-b from-transparent via-[#050609] to-[#0c0d10] px-5 pb-24 pt-[85vh]"><div className="mx-auto max-w-6xl"><div className="rounded-[32px] border border-white/10 bg-white/[.055] p-6 backdrop-blur-2xl lg:hidden"><Configurator {...{config,setConfig,explore,setExplore,preset,choosePreset,setDoor}}/></div><div className="mt-20 grid gap-10 border-t border-white/10 pt-16 lg:grid-cols-2"><div><p className="text-sm text-[#64d2ff]">A REALISTIC FOUNDATION</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em]">Preview the feeling. Book the real fleet.</h2></div><div className="text-base leading-7 text-white/55"><p>Paint and upholstery selections here are visual previews on the articulated Drift Concept model. They do not modify or promise a specific rental vehicle.</p><p className="mt-4">Continue to the catalogue to select an actually available vehicle, its listed specifications and genuinely bookable rental dates.</p><a href="/#browse" className="mt-7 inline-flex h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-semibold text-black"><ArrowLeft className="size-4"/>Explore 70 real vehicles</a></div></div></div></section>
  </main>;
}

function CarScene({config,progress,guidedPreset,preset,explore}:{config:Config;progress:number;guidedPreset:CameraPreset;preset:CameraPreset;explore:boolean}){
  const car=useRef<Group>(null); const wheels=useRef<Mesh[]>([]); const door=useRef<Group>(null); const glass=useRef<Mesh>(null); const {camera}=useThree();
  const active=explore?preset:guidedPreset; const anchor=cameraAnchors[active]; const target=useMemo(()=>new Vector3(),[]);
  useFrame((_,delta)=>{ const a=1-Math.exp(-delta*3.4); if(!explore){camera.position.lerp(target.set(...anchor.position),a); camera.lookAt(...anchor.target)} if(car.current){car.current.position.x=Math.sin(progress*Math.PI)*.42;car.current.rotation.y=MathUtils.lerp(-.08,.08,progress)} wheels.current.forEach(w=>w.rotation.x=-progress*Math.PI*5); if(door.current)door.current.rotation.y=MathUtils.lerp(door.current.rotation.y,(config.doorOpen||(!explore&&progress>.42&&progress<.84))?-1.08:0,a); if(glass.current)glass.current.position.y=MathUtils.lerp(glass.current.position.y,config.windowDown?-.42:.02,a); });
  return <group ref={car} position={[0,0,0]}><VehicleBody paint={config.paint} upholstery={config.upholstery} door={door} glass={glass} wheels={wheels}/></group>;
}

function VehicleBody({paint,upholstery,door,glass,wheels}:{paint:string;upholstery:string;door:React.RefObject<Group|null>;glass:React.RefObject<Mesh|null>;wheels:React.MutableRefObject<Mesh[]>}){
  const paintColor=new Color(paint); const wheelPositions:[[number,number,number],number][]=[[[-2.05,-.18,1.35],0],[[-2.05,-.18,-1.35],0],[[2.05,-.18,1.35],0],[[2.05,-.18,-1.35],0]];
  return <group rotation={[0,-Math.PI/2,0]} scale={.82}><RoundedBox args={[4.9,.82,2.15]} radius={.28} smoothness={5} position={[0,.18,0]} castShadow receiveShadow><meshStandardMaterial color={paintColor} metalness={.86} roughness={.18}/></RoundedBox><RoundedBox args={[2.8,.72,1.84]} radius={.24} smoothness={5} position={[-.15,.88,0]} castShadow><meshPhysicalMaterial color="#171b22" metalness={.2} roughness={.12} transmission={.25} transparent opacity={.82}/></RoundedBox><mesh position={[1.42,.88,0]} rotation={[0,0,-.45]}><boxGeometry args={[.08,.8,1.72]}/><meshPhysicalMaterial color="#9ec8e8" transmission={.7} transparent opacity={.42} roughness={.08}/></mesh><mesh position={[-1.45,.86,0]} rotation={[0,0,.42]}><boxGeometry args={[.08,.72,1.72]}/><meshPhysicalMaterial color="#7da8ca" transmission={.65} transparent opacity={.38}/></mesh>
    <group ref={door} position={[.35,.38,1.09]}><RoundedBox args={[1.62,.82,.1]} radius={.08} smoothness={3} position={[-.81,0,0]} castShadow><meshStandardMaterial color={paintColor} metalness={.84} roughness={.2}/></RoundedBox><mesh ref={glass} position={[-.82,.64,0]}><boxGeometry args={[1.4,.62,.055]}/><meshPhysicalMaterial color="#89b8d8" transmission={.75} transparent opacity={.48} roughness={.06}/></mesh></group>
    <group position={[.2,.55,0]}>{[-.72,.72].map((z,i)=><group key={z} position={[-.5,0,z]}><RoundedBox args={[.66,.85,.54]} radius={.14} smoothness={3}><meshStandardMaterial color={upholstery} roughness={.72}/></RoundedBox><RoundedBox args={[.55,.62,.5]} radius={.14} smoothness={3} position={[-.17,.62,0]}><meshStandardMaterial color={upholstery} roughness={.78}/></RoundedBox></group>)}</group>
    {wheelPositions.map(([position],i)=><group key={i} position={position} rotation={[Math.PI/2,0,0]}><mesh ref={node=>{if(node)wheels.current[i]=node}} castShadow><cylinderGeometry args={[.52,.52,.34,32]}/><meshStandardMaterial color="#08090b" roughness={.78}/></mesh><mesh position={[0,.18,0]}><cylinderGeometry args={[.29,.29,.36,12]}/><meshStandardMaterial color="#bac0c8" metalness={.9} roughness={.2}/></mesh></group>)}<mesh position={[2.48,.12,0]}><boxGeometry args={[.05,.25,1.25]}/><meshStandardMaterial color="#dff5ff" emissive="#89d7ff" emissiveIntensity={3}/></mesh><mesh position={[-2.48,.12,0]}><boxGeometry args={[.05,.22,1.18]}/><meshStandardMaterial color="#ff2d38" emissive="#ff0015" emissiveIntensity={2}/></mesh></group>;
}

type ConfiguratorProps={config:Config;setConfig:React.Dispatch<React.SetStateAction<Config>>;explore:boolean;setExplore:(v:boolean)=>void;preset:CameraPreset;choosePreset:(v:CameraPreset)=>void;setDoor:(v:boolean)=>void};
function Configurator({config,setConfig,explore,setExplore,preset,choosePreset,setDoor}:ConfiguratorProps){return <div><div className="flex items-center justify-between"><div><p className="text-xs font-semibold tracking-[.16em] text-[#64d2ff]">CONFIGURE</p><p className="mt-1 text-sm text-white/50">Visual preview only</p></div><Button variant="ghost" className="rounded-full text-white hover:bg-white/10 hover:text-white" onClick={()=>{setExplore(false);setDoor(false)}}><RotateCcw/>Resume story</Button></div><div className="mt-6"><p className="text-xs text-white/45">Camera</p><div className="mt-2 grid grid-cols-4 gap-1">{(['front','side','rear','interior'] as CameraPreset[]).map(x=><button key={x} onClick={()=>choosePreset(x)} className={`rounded-xl px-2 py-2 text-xs capitalize ${explore&&preset===x?'bg-white text-black':'bg-white/5 text-white/65 hover:bg-white/10'}`}>{x}</button>)}</div></div><div className="mt-5"><p className="text-xs text-white/45">Paint finish</p><div className="mt-2 flex gap-2">{paints.map(x=><button key={x.value} aria-label={x.name} title={x.name} onClick={()=>{setExplore(true);setConfig(c=>({...c,paint:x.value}))}} className={`size-9 rounded-full border-2 ${config.paint===x.value?'border-white':'border-white/15'}`} style={{background:x.value}}/>)}</div></div><div className="mt-5"><p className="text-xs text-white/45">Upholstery preview</p><div className="mt-2 flex gap-2">{leathers.map(x=><button key={x.value} onClick={()=>{setExplore(true);choosePreset('interior');setConfig(c=>({...c,upholstery:x.value}))}} className={`rounded-full border px-3 py-2 text-xs ${config.upholstery===x.value?'border-white bg-white text-black':'border-white/15 text-white/65'}`}>{x.name}</button>)}</div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setDoor(!config.doorOpen)} className={`flex min-h-12 items-center justify-center gap-2 rounded-2xl text-xs ${config.doorOpen?'bg-[#0a84ff]':'bg-white/8'}`}><DoorOpen className="size-4"/>{config.doorOpen?'Close door':'Open door'}</button><button onClick={()=>{setExplore(true);setConfig(c=>({...c,windowDown:!c.windowDown}))}} className={`flex min-h-12 items-center justify-center gap-2 rounded-2xl text-xs ${config.windowDown?'bg-[#0a84ff]':'bg-white/8'}`}><Wind className="size-4"/>{config.windowDown?'Raise window':'Lower window'}</button></div><p className="mt-4 flex items-start gap-2 text-[11px] leading-4 text-white/35"><Check className="mt-.5 size-4 shrink-0"/>Controls affect the articulated concept model, not rental inventory.</p></div>}
function Poster(){return <div className="absolute inset-0"><img src="/og.png" alt="Drift vehicles" className="h-full w-full object-cover opacity-70"/><div className="absolute inset-0 bg-black/45"/><p className="absolute bottom-24 left-1/2 -translate-x-1/2 rounded-full bg-black/60 px-4 py-2 text-xs text-white/70">3D unavailable — showing vehicle photography</p></div>}
function sceneLabel(scene:SceneState){return ({intro:'Arrival · front three-quarter',exterior:'Exterior · profile and motion',doorOpening:'Door opening · cabin revealed',interior:'Interior · crafted around the driver',configuring:'Materials · make it yours',returning:'Finish · return to the road'})[scene]}
